publish_mode: editorial_workflow
media_folder: /public/uploaded
public_folder: /uploaded

backend:
  name: github
  repo: s1lv3r-website/astro-rewrite
  branch: master
  squash_merges: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/_blogposts"
    create: true
    slug: "{{ slug }}"
    preview_path: blog/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - label: "Description"
        name: "description"
        widget: "string"
        required: false
        optional: true

      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"
        default: "{{now}}"
      - label: "Update Date"
        name: "updatedDate"
        widget: "datetime"
        optional: true
        required: false

      - label: Socials
        name: socials
        widget: list
        optional: true
        required: false
        min: 0
        fields:
          - { label: Site name, name: site, widget: string }
          - { label: URL, name: url, widget: string }

      - { label: "Body", name: "body", widget: "markdown" }
