publish_mode: editorial_workflow
media_folder: /public/uploaded
public_folder: /uploaded
local_backend: true
backend:
  name: git-gateway
  branch: master
  squash_merges: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogposts"
    create: true
    slug: "{{ slug }}"
    preview_path: blog/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          default: "{{now}}",
        }
      - {
          label: "Update Date",
          name: "updatedDate",
          widget: "datetime",
          optional: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: Show in UI, name: showInUI, widget: boolean }
